[package]
name = "siderite"
version = "0.0.1"
authors = ["Bond-009 <bond.009@outlook.com>"]
keywords = ["siderite", "minecraft", "server"]
repository = "https://github.com/Bond-009/siderite.git"

[[bin]]
name = "siderite"
path = "server/main.rs"
doc = false
test = false
bench = false

[lib]
name = "siderite"
path = "src/lib.rs"

[dependencies]
log = "0.4.1"
env_logger = "0.5.10"
byteorder = "1.2.2"
openssl = "0.10.8"
num-derive = "0.2.1"
num-traits = "0.2.4"
rand = "0.5"
serde_json = "1.0.17"
