[package]
name = "siderite"
version = "0.0.1"
authors = ["Bond-009 <bond.009@outlook.com>"]
keywords = ["siderite", "minecraft", "server"]
repository = "https://github.com/Bond-009/siderite.git"
edition = "2018"

[[bin]]
name = "siderite"
path = "server/main.rs"
doc = false
test = false
bench = false

[lib]
name = "siderite"
path = "src/lib.rs"

[dependencies]
#base64 = "0.10.0"
byteorder = "1.2.7"
circbuf = "0.1.4"
env_logger = "0.6.0"
hex = "0.3.2"
log = "0.4.6"
openssl = "0.10.15"
#nalgebra = "0.16"
num-derive = "0.2"
num-traits = "0.2.6"
rand = "0.6"
serde_json = "1.0.33"

[dependencies.uuid]
version = "0.7"
features = ["v3"]

[dependencies.mojang]
git = "https://gitlab.com/siderite/mojang-rs.git"
